[features]
seeds = false
skip-lint = false

[programs.devnet]
switch = "8hK7vGkWap7CwfWnZG8igqz5uxevUDTbhoeuCcwgvpYq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/amrit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
